### ISSUE TITLE
Max 255 characters

### ISSUE THREAD

**Issue by simple-nicholas** [mblode/sprout-forms-tables#2]
Currently, the database column type is using the default - which appears to be varchar(255). While usable, this is quite limiting.

One solution is to update the field class (src/integrations/sproutforms/fields/Table.php) to use the text column type instead. ie:

```php
use yii\db\Schema; // near the top with the other use statements

...

public function getContentColumnType(): string // in the class itself
{
    return Schema::TYPE_TEXT;
}
```

**Comment by mblode** [comment]
Thank you! I'll have a look at this now and push an update 😄

**Comment by mblode** [comment]
I've pushed an update, let me know if that fixed your issue 👍

**Comment by simple-nicholas** [comment]
Hey, thanks for the quick turn-around!

I think autocomplete tripped you up though, the column type is now integer?

**Comment by mblode** [comment]
Whoops! Yeah I completely missed that so I've just pushed version 1.0.9 that fixes the error
