### ISSUE TITLE
Version 1.0.6 is the most recent version in the plugin store, not version 1.0.9

### ISSUE THREAD

**Issue by BenParizek** [mblode/sprout-forms-tables#3]
@mblode I noticed that the version of this plugin in the repo currently works fine but the one in the Plugin Store is currently an older version and throws a few errors with the latest version of Sprout Forms.

It appears you have the v1.0.9 tag in your composer file and as a tag in the repo so I reached out to Pixel and Tonic and asked what the reason may be that this isn't showing the latest version in the store. Their first reply was that perhaps the most recent version isn't referenced in the CHANGELOG:

```
Not too sure what happened here. Normally, the three things I look for are the composer.json, the actual release and the CHANGELOG (docs).

Here I can see the CHANGELOG isn't up to date so could you try that, please?
```

I'm not sure if that will fix things but if you have a chance, perhaps you can give that a try.

**Comment by mblode** [comment]
You can now download 1.0.10 from the plugin store. Thank you for letting me know!
