### ISSUE TITLE
Issue with latest version of Sprout Forms

### ISSUE THREAD

**Issue by jwrudzin** [mblode/sprout-forms-tables#4]
It appears there is a bug when using this plugin with the latest version of Sprout Forms (the bug appears to have started with Sprout Forms 3.12.0).

Before any migrations are able to run, the error below appears after updating Sprout Forms via composer.

<img width="1245" alt="Screen Shot 2020-10-25 at 12 49 29 PM" src="https://user-images.githubusercontent.com/18213990/97648278-b276a280-1a2a-11eb-8ea9-e66707ca40a5.png">

It appears this issue is related to this section from the Sprout Forms docs:

"Sprout Forms v3.12.0 includes a small breaking change to the getFrontEndInputHtml method in your Form Field classes. This was necessary to support more refined targeting for Rendering Options including the targeting of error classes on input fields to better support using Rendering Options for front-end frameworks such as Bootstrap."

[Relevant info here](https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#upgrading-to-forms-v3-12-0)

Any chance you could update the plugin to fix this issue? Thanks!

**Comment by jwrudzin** [comment]
Just checking in here to see if there's any chance we'll be able to get a fix for this issue? Thanks!

**Comment by mblode** [comment]
Thanks for creating this issue! I've pushed an update to resolve it. Would you be able to update to 1.0.11 and let me know if it works?
